GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Attack On Titains"
}

###

PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
 "title":"star wars"
}

###

DELETE http://localhost:3001/books/4 HTTP/1.1
Content-Type: application/json




